# Generated by Django 4.2.6 on 2023-10-19 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_player_id_player_picture_player_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='test', upload_to='media/%y', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
    ]
