# Generated by Django 4.2.6 on 2023-10-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pid',
            field=models.CharField(default='2046808c', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
