# Generated by Django 4.2.6 on 2023-10-19 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_player_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
